In [3]:
from biopandas.pdb import PandasPdb
pdb1=PandasPdb().read_pdb('/home/ailon/Desktop/python_practice/1t46_STI_A.txt')
#데이터를 파싱하고 head 부분만 불러온다.

In [5]:
pdb2=pdb1.df['ATOM']

In [6]:
pdb2.head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0        ATOM            1                 N                  GLY           
1        ATOM            2                CA                  GLY           
2        ATOM            3                 C                  GLY           
3        ATOM            4                 O                  GLY           
4        ATOM            5                 N                  ASN           

  chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0        A             565            ...  22.652   20.382   20.682   
1        A             565            ...  23.584   21.304   19.964   
2        A             565            ...  22.927   22.199   18.919   
3        A             565            ...  23.603   22.680   18.003   
4        A             566            ...  21.622   22.442   19.061   

   occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0        1.0     26.37                                  N    NaN         0  
1        1.0     26.85                                  C    NaN         1  
2        1.0     27.20                                  C    NaN         2  
3        1.0     28.35                                  O    NaN         3  
4        1.0     27.12                                  N    NaN         4  

[5 rows x 21 columns]

In [5]:
pdb2['atom_name']=='CA'
# Atom name이 ‘CA’인지 질문해 결과를 T/F인 시리즈로 출력한다.

0       True
1      False
2      False
3      False
4      False
       ...  
498    False
499    False
500    False
501    False
502    False
Name: atom_name, Length: 503, dtype: bool

In [6]:
pdb2.loc[pdb2['atom_name']=='CA',:]
#불리언 인덱싱으로 atom_name이 ‘CA’인 행만 추출한다.

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0          ATOM          262                CA                  LEU           
8          ATOM          270                CA                  GLY           
12         ATOM          274                CA                  ALA           
17         ATOM          299                CA                  GLY           
21         ATOM          303                CA                  LYS           
..          ...          ...     ...       ...     ...          ...     ...   
464        ATOM         1384                CA                  GLY           
468        ATOM         1388                CA                  LEU           
476        ATOM         1396                CA                  ALA           
481        ATOM         1401                CA                  ARG           
492        ATOM         1467                CA                  TYR           

    chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0          A             595            ...  31.938   29.660   49.840   
8          A             596            ...  31.424   32.568   47.447   
12         A             597            ...  29.702   35.947   47.302   
17         A             601            ...  23.924   36.450   46.017   
21         A             602            ...  26.165   34.154   48.009   
..       ...             ...       ...  ...     ...      ...      ...   
464        A             812            ...  26.416   33.292   38.708   
468        A             813            ...  24.982   35.770   41.238   
476        A             814            ...  27.459   34.429   43.805   
481        A             815            ...  30.703   35.641   42.235   
492        A             823            ...  36.278   39.771   34.520   

     occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0          1.0     21.57                                  C    NaN         1  
8          1.0     21.44                                  C    NaN         9  
12         1.0     23.14                                  C    NaN        13  
17         1.0     28.91                                  C    NaN        18  
21         1.0     22.52                                  C    NaN        22  
..         ...       ...      ...        ...            ...    ...       ...  
464        1.0     21.25                                  C    NaN       465  
468        1.0     21.38                                  C    NaN       469  
476        1.0     19.38                                  C    NaN       477  
481        1.0     24.55                                  C    NaN       482  
492        1.0     21.78                                  C    NaN       493  

[67 rows x 21 columns]

In [7]:
pdb3=pdb2.loc[pdb2['atom_name']=='CA',:]

In [8]:
pdb3.loc[:,['residue_name','residue_number','chain_id','x_coord','y_coord','z_coord']]
# Residue를 구분하는 데 사용되는 column인 'residue_name','residue_number','chain_id' 와 
#거리를 구하는 데 사용될 좌표 column 'x_coord','y_coord','z_coord'만 추출한다.

residue_name  residue_number chain_id  x_coord  y_coord  z_coord
0            LEU             595        A   31.938   29.660   49.840
8            GLY             596        A   31.424   32.568   47.447
12           ALA             597        A   29.702   35.947   47.302
17           GLY             601        A   23.924   36.450   46.017
21           LYS             602        A   26.165   34.154   48.009
..           ...             ...      ...      ...      ...      ...
464          GLY             812        A   26.416   33.292   38.708
468          LEU             813        A   24.982   35.770   41.238
476          ALA             814        A   27.459   34.429   43.805
481          ARG             815        A   30.703   35.641   42.235
492          TYR             823        A   36.278   39.771   34.520

[67 rows x 6 columns]

In [9]:
pdb4=pdb3.loc[:,['residue_name','residue_number','chain_id','x_coord','y_coord','z_coord']]

In [10]:
from math import *

In [43]:
def euclidean_distance(x, y):
    return sqrt(sum(pow(a - b, 2) for a, b in zip(x, y)))

print(euclidean_distance([31.938,29.660,49.840], [31.424,32.568,47.447]))
#Euclidean distance 구하는 시용자 함수를 만든다.
#첫 번째 행과 두 번째 행의 좌표를 대입해 보았을 때 정상적으로 작동한다.

3.8009352796384195


In [13]:
list1=[1,2,3,4,5]
for i in range(len(list1)):
    for j in range(i+1,len(list1)):
        sum1=list1[i]+list1[j]
        print(sum1)
#문제를 단순화시켜 이중 for 문으로 list의 모든 원소끼리의 합을 중복 없이 구해 보았다.(1+2, 1+3,1+4,...3+5,4+5)
#list1의 원소가 5개이므로, 모든 원소끼리의 합의 개수는 5C2개가 출력되어야 하고, 코드 실행 결과 정상적으로 작동한다.

3
4
5
6
5
6
7
7
8
9


In [14]:
for i in range(len(pdb4)):
    for j in range(i+1,len(pdb4)):
        residue_pair1_1=pdb4.iloc[i]['residue_name']
        residue_pair2_1=pdb4.iloc[j]['residue_name']
        print(residue_pair1,residue_pair2)
#우선 이중 for문으로 residue name 쌍을 출력해 보았다.
#첫 번째 row에 있는 LEU가 자기 자신은 제외하고 두 번째 row에 있는 GLY부터 차례로 쌍을 이뤄 출력된다.

LEU GLY
LEU ALA
LEU GLY
LEU LYS
LEU VAL
LEU VAL
LEU VAL
LEU ALA
LEU VAL
LEU LYS
LEU MET
LEU ALA
LEU LEU
LEU MET
LEU SER
LEU GLU
LEU LEU
LEU LYS
LEU VAL
LEU LEU
LEU SER
LEU LEU
LEU GLY
LEU ASN
LEU HIS
LEU ASN
LEU ILE
LEU VAL
LEU ASN
LEU LEU
LEU LEU
LEU GLY
LEU LEU
LEU VAL
LEU ILE
LEU THR
LEU GLU
LEU TYR
LEU CYS
LEU GLY
LEU ASP
LEU LEU
LEU MET
LEU LEU
LEU ILE
LEU HIS
LEU ASP
LEU LEU
LEU ALA
LEU ALA
LEU ARG
LEU ASN
LEU ILE
LEU LEU
LEU LEU
LEU THR
LEU LYS
LEU ILE
LEU CYS
LEU ASP
LEU PHE
LEU GLY
LEU LEU
LEU ALA
LEU ARG
LEU TYR
GLY ALA
GLY GLY
GLY LYS
GLY VAL
GLY VAL
GLY VAL
GLY ALA
GLY VAL
GLY LYS
GLY MET
GLY ALA
GLY LEU
GLY MET
GLY SER
GLY GLU
GLY LEU
GLY LYS
GLY VAL
GLY LEU
GLY SER
GLY LEU
GLY GLY
GLY ASN
GLY HIS
GLY ASN
GLY ILE
GLY VAL
GLY ASN
GLY LEU
GLY LEU
GLY GLY
GLY LEU
GLY VAL
GLY ILE
GLY THR
GLY GLU
GLY TYR
GLY CYS
GLY GLY
GLY ASP
GLY LEU
GLY MET
GLY LEU
GLY ILE
GLY HIS
GLY ASP
GLY LEU
GLY ALA
GLY ALA
GLY ARG
GLY ASN
GLY ILE
GLY LEU
GLY LEU
GLY THR
GLY LYS
GLY ILE
GLY CYS
GLY ASP


LEU CYS
LEU ASP
LEU PHE
LEU GLY
LEU LEU
LEU ALA
LEU ARG
LEU TYR
LEU GLY
LEU LEU
LEU VAL
LEU ILE
LEU THR
LEU GLU
LEU TYR
LEU CYS
LEU GLY
LEU ASP
LEU LEU
LEU MET
LEU LEU
LEU ILE
LEU HIS
LEU ASP
LEU LEU
LEU ALA
LEU ALA
LEU ARG
LEU ASN
LEU ILE
LEU LEU
LEU LEU
LEU THR
LEU LYS
LEU ILE
LEU CYS
LEU ASP
LEU PHE
LEU GLY
LEU LEU
LEU ALA
LEU ARG
LEU TYR
GLY LEU
GLY VAL
GLY ILE
GLY THR
GLY GLU
GLY TYR
GLY CYS
GLY GLY
GLY ASP
GLY LEU
GLY MET
GLY LEU
GLY ILE
GLY HIS
GLY ASP
GLY LEU
GLY ALA
GLY ALA
GLY ARG
GLY ASN
GLY ILE
GLY LEU
GLY LEU
GLY THR
GLY LYS
GLY ILE
GLY CYS
GLY ASP
GLY PHE
GLY GLY
GLY LEU
GLY ALA
GLY ARG
GLY TYR
LEU VAL
LEU ILE
LEU THR
LEU GLU
LEU TYR
LEU CYS
LEU GLY
LEU ASP
LEU LEU
LEU MET
LEU LEU
LEU ILE
LEU HIS
LEU ASP
LEU LEU
LEU ALA
LEU ALA
LEU ARG
LEU ASN
LEU ILE
LEU LEU
LEU LEU
LEU THR
LEU LYS
LEU ILE
LEU CYS
LEU ASP
LEU PHE
LEU GLY
LEU LEU
LEU ALA
LEU ARG
LEU TYR
VAL ILE
VAL THR
VAL GLU
VAL TYR
VAL CYS
VAL GLY
VAL ASP
VAL LEU
VAL MET
VAL LEU
VAL ILE
VAL HIS
VAL ASP
VAL LEU
VAL ALA


In [15]:
for i in range(len(pdb4)):
    for j in range(i+1,len(pdb4)):
        residue_pair1_2=pdb4.iloc[i][['residue_name','residue_number','chain_id']]
        residue_pair2_2=pdb4.iloc[j][['residue_name','residue_number','chain_id']]
        print(residue_pair1,residue_pair2)
#residue name에 이어 residue number, chain id도 함께 출력해 보았다.
#출력하는 열이 2개 이상일 경우, 이렇게 column name까지 표시된다. 최종 output 이미지 참고해 코드를 수정해야 한다.
#iloc 때문인 것 같다. Column name이 아닌 값만을 가져오는 Pandas 함수 찾아보기

residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name      GLY
residue_number    596
chain_id            A
Name: 8, dtype: object
residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object
residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name      GLY
residue_number    601
chain_id            A
Name: 17, dtype: object
residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name      LYS
residue_number    602
chain_id            A
Name: 21, dtype: object
residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object
residue_name      LEU
residue_number    595
chain_id            A
Name: 0, dtype: object residue_name     

Name: 12, dtype: object residue_name      MET
residue_number    780
chain_id            A
Name: 312, dtype: object
residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object residue_name      LEU
residue_number    783
chain_id            A
Name: 320, dtype: object
residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object residue_name      ILE
residue_number    789
chain_id            A
Name: 328, dtype: object
residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object residue_name      HIS
residue_number    790
chain_id            A
Name: 336, dtype: object
residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object residue_name      ASP
residue_number    792
chain_id            A
Name: 346, dtype: object
residue_name      ALA
residue_number    597
chain_id            A
Name: 12, dtype: object residue_name      LEU
residue_number    793
chain_id            A
Name:

Name: 30, dtype: object residue_name      SER
residue_number    639
chain_id            A
Name: 101, dtype: object
residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object
residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object residue_name      LEU
residue_number    641
chain_id            A
Name: 116, dtype: object
residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object residue_name      LYS
residue_number    642
chain_id            A
Name: 124, dtype: object
residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object
residue_name      VAL
residue_number    603
chain_id            A
Name: 30, dtype: object residue_name      LEU
residue_number    644
chain_id            A
Name:

Name: 44, dtype: object residue_name      ARG
residue_number    796
chain_id            A
Name: 372, dtype: object
residue_name      VAL
residue_number    620
chain_id            A
Name: 44, dtype: object residue_name      ASN
residue_number    797
chain_id            A
Name: 383, dtype: object
residue_name      VAL
residue_number    620
chain_id            A
Name: 44, dtype: object residue_name      ILE
residue_number    798
chain_id            A
Name: 391, dtype: object
residue_name      VAL
residue_number    620
chain_id            A
Name: 44, dtype: object residue_name      LEU
residue_number    799
chain_id            A
Name: 399, dtype: object
residue_name      VAL
residue_number    620
chain_id            A
Name: 44, dtype: object residue_name      LEU
residue_number    800
chain_id            A
Name: 407, dtype: object
residue_name      VAL
residue_number    620
chain_id            A
Name: 44, dtype: object residue_name      THR
residue_number    806
chain_id            A
Name:

Name: 63, dtype: object residue_name      TYR
residue_number    672
chain_id            A
Name: 274, dtype: object
residue_name      LYS
residue_number    623
chain_id            A
Name: 63, dtype: object residue_name      CYS
residue_number    673
chain_id            A
Name: 286, dtype: object
residue_name      LYS
residue_number    623
chain_id            A
Name: 63, dtype: object residue_name      GLY
residue_number    676
chain_id            A
Name: 292, dtype: object
residue_name      LYS
residue_number    623
chain_id            A
Name: 63, dtype: object residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object
residue_name      LYS
residue_number    623
chain_id            A
Name: 63, dtype: object residue_name      LEU
residue_number    678
chain_id            A
Name: 304, dtype: object
residue_name      LYS
residue_number    623
chain_id            A
Name: 63, dtype: object residue_name      MET
residue_number    780
chain_id            A
Name:

Name: 85, dtype: object residue_name      LEU
residue_number    667
chain_id            A
Name: 235, dtype: object
residue_name      LEU
residue_number    637
chain_id            A
Name: 85, dtype: object residue_name      VAL
residue_number    668
chain_id            A
Name: 243, dtype: object
residue_name      LEU
residue_number    637
chain_id            A
Name: 85, dtype: object residue_name      ILE
residue_number    669
chain_id            A
Name: 250, dtype: object
residue_name      LEU
residue_number    637
chain_id            A
Name: 85, dtype: object residue_name      THR
residue_number    670
chain_id            A
Name: 258, dtype: object
residue_name      LEU
residue_number    637
chain_id            A
Name: 85, dtype: object residue_name      GLU
residue_number    671
chain_id            A
Name: 265, dtype: object
residue_name      LEU
residue_number    637
chain_id            A
Name: 85, dtype: object residue_name      TYR
residue_number    672
chain_id            A
Name:

Name: 107, dtype: object residue_name      TYR
residue_number    672
chain_id            A
Name: 274, dtype: object
residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object residue_name      CYS
residue_number    673
chain_id            A
Name: 286, dtype: object
residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object residue_name      GLY
residue_number    676
chain_id            A
Name: 292, dtype: object
residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object
residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object residue_name      LEU
residue_number    678
chain_id            A
Name: 304, dtype: object
residue_name      GLU
residue_number    640
chain_id            A
Name: 107, dtype: object residue_name      MET
residue_number    780
chain_id            A

Name: 133, dtype: object residue_name      ALA
residue_number    795
chain_id            A
Name: 367, dtype: object
residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object residue_name      ARG
residue_number    796
chain_id            A
Name: 372, dtype: object
residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object residue_name      ASN
residue_number    797
chain_id            A
Name: 383, dtype: object
residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object residue_name      ILE
residue_number    798
chain_id            A
Name: 391, dtype: object
residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object residue_name      LEU
residue_number    799
chain_id            A
Name: 399, dtype: object
residue_name      VAL
residue_number    643
chain_id            A
Name: 133, dtype: object residue_name      LEU
residue_number    800
chain_id            A

Name: 162, dtype: object residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object
residue_name      GLY
residue_number    648
chain_id            A
Name: 162, dtype: object residue_name      GLY
residue_number    658
chain_id            A
Name: 231, dtype: object
residue_name      GLY
residue_number    648
chain_id            A
Name: 162, dtype: object residue_name      LEU
residue_number    667
chain_id            A
Name: 235, dtype: object
residue_name      GLY
residue_number    648
chain_id            A
Name: 162, dtype: object residue_name      VAL
residue_number    668
chain_id            A
Name: 243, dtype: object
residue_name      GLY
residue_number    648
chain_id            A
Name: 162, dtype: object residue_name      ILE
residue_number    669
chain_id            A
Name: 250, dtype: object
residue_name      GLY
residue_number    648
chain_id            A
Name: 162, dtype: object residue_name      THR
residue_number    670
chain_id            A

Name: 184, dtype: object residue_name      ALA
residue_number    814
chain_id            A
Name: 476, dtype: object
residue_name      ASN
residue_number    652
chain_id            A
Name: 184, dtype: object residue_name      ARG
residue_number    815
chain_id            A
Name: 481, dtype: object
residue_name      ASN
residue_number    652
chain_id            A
Name: 184, dtype: object residue_name      TYR
residue_number    823
chain_id            A
Name: 492, dtype: object
residue_name      ILE
residue_number    653
chain_id            A
Name: 192, dtype: object residue_name      VAL
residue_number    654
chain_id            A
Name: 200, dtype: object
residue_name      ILE
residue_number    653
chain_id            A
Name: 192, dtype: object residue_name      ASN
residue_number    655
chain_id            A
Name: 207, dtype: object
residue_name      ILE
residue_number    653
chain_id            A
Name: 192, dtype: object residue_name      LEU
residue_number    656
chain_id            A

Name: 223, dtype: object residue_name      GLY
residue_number    676
chain_id            A
Name: 292, dtype: object
residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object
residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object residue_name      LEU
residue_number    678
chain_id            A
Name: 304, dtype: object
residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object residue_name      MET
residue_number    780
chain_id            A
Name: 312, dtype: object
residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object residue_name      LEU
residue_number    783
chain_id            A
Name: 320, dtype: object
residue_name      LEU
residue_number    657
chain_id            A
Name: 223, dtype: object residue_name      ILE
residue_number    789
chain_id            A

Name: 250, dtype: object residue_name      ARG
residue_number    815
chain_id            A
Name: 481, dtype: object
residue_name      ILE
residue_number    669
chain_id            A
Name: 250, dtype: object residue_name      TYR
residue_number    823
chain_id            A
Name: 492, dtype: object
residue_name      THR
residue_number    670
chain_id            A
Name: 258, dtype: object residue_name      GLU
residue_number    671
chain_id            A
Name: 265, dtype: object
residue_name      THR
residue_number    670
chain_id            A
Name: 258, dtype: object residue_name      TYR
residue_number    672
chain_id            A
Name: 274, dtype: object
residue_name      THR
residue_number    670
chain_id            A
Name: 258, dtype: object residue_name      CYS
residue_number    673
chain_id            A
Name: 286, dtype: object
residue_name      THR
residue_number    670
chain_id            A
Name: 258, dtype: object residue_name      GLY
residue_number    676
chain_id            A

Name: 296, dtype: object residue_name      LYS
residue_number    807
chain_id            A
Name: 422, dtype: object
residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object residue_name      ILE
residue_number    808
chain_id            A
Name: 431, dtype: object
residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object residue_name      CYS
residue_number    809
chain_id            A
Name: 439, dtype: object
residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object residue_name      ASP
residue_number    810
chain_id            A
Name: 445, dtype: object
residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object residue_name      PHE
residue_number    811
chain_id            A
Name: 453, dtype: object
residue_name      ASP
residue_number    677
chain_id            A
Name: 296, dtype: object residue_name      GLY
residue_number    812
chain_id            A

Name: 362, dtype: object residue_name      ARG
residue_number    796
chain_id            A
Name: 372, dtype: object
residue_name      ALA
residue_number    794
chain_id            A
Name: 362, dtype: object residue_name      ASN
residue_number    797
chain_id            A
Name: 383, dtype: object
residue_name      ALA
residue_number    794
chain_id            A
Name: 362, dtype: object residue_name      ILE
residue_number    798
chain_id            A
Name: 391, dtype: object
residue_name      ALA
residue_number    794
chain_id            A
Name: 362, dtype: object residue_name      LEU
residue_number    799
chain_id            A
Name: 399, dtype: object
residue_name      ALA
residue_number    794
chain_id            A
Name: 362, dtype: object residue_name      LEU
residue_number    800
chain_id            A
Name: 407, dtype: object
residue_name      ALA
residue_number    794
chain_id            A
Name: 362, dtype: object residue_name      THR
residue_number    806
chain_id            A

In [39]:
#for i in range(len(pdb4)):
#    for j in range(i+1,len(pdb4)):
#       residue_pair1=pdb4.iloc[i][['x_coord','y_coord','z_coord']].values
#        residue_pair2=pdb4.iloc[j][['x_coord','y_coord','z_coord']].values
#        print(residue_pair1,residue_pair2)
#        print(euclidean_distance(residue_pair1,residue_pair2))
#euclidean_distance 함수를 전체 좌표에 적용하기에 앞서 x좌표와 sum함수만을 사용해 테스트를 진행했다.
#가능한 모든 residue pair조합의 x좌표만을 추출하고 단순히 합을 출력했는데, 
#+를 사용했을 때는 출력이 정상적으로 되지만 sum함수를 사용하자 'numpy.float64' object is not iterable 에러가 발생했다.

[31.938 29.66 49.84] [31.424 32.568 47.447]
3.8009352796384195
[31.938 29.66 49.84] [29.702 35.947 47.302]
7.139153241106401
[31.938 29.66 49.84] [23.924 36.45 46.017]
11.17781843652866
[31.938 29.66 49.84] [26.165 34.154 48.009]
7.541626217202762
[31.938 29.66 49.84] [26.883 30.457 48.394]
5.317814400672518
[31.938 29.66 49.84] [27.303 29.045 51.883]
5.102479691287362
[31.938 29.66 49.84] [25.261 20.813 51.393]
11.192119861759881
[31.938 29.66 49.84] [25.93 24.037 49.521]
8.23504426217613
[31.938 29.66 49.84] [23.24 26.704 49.586]
9.190084656846205
[31.938 29.66 49.84] [22.88 29.616 47.183]
9.439753651446631
[31.938 29.66 49.84] [20.839 32.461 48.545]
11.520001171874942
[31.938 29.66 49.84] [17.342 34.633 37.984]
19.450930080589977
[31.938 29.66 49.84] [17.862 32.324 40.961]
16.85429657387101
[31.938 29.66 49.84] [14.533 30.604 40.293]
19.873861476824278
[31.938 29.66 49.84] [15.527 30.274 36.636]
21.07234047276192
[31.938 29.66 49.84] [18.864 28.694 37.642]
17.906809766119704
[31.938

<ipython-input-33-8468382ea51f>:2: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sqrt(numpy.sum(pow(a - b, 2) for a, b in zip(x, y)))


 [27.356 27.5 29.894]
18.757192033990595
[23.924 36.45 46.017] [31.311 31.071 31.701]
16.98379421684095
[23.924 36.45 46.017] [33.232 27.844 31.485]
19.28421955900731
[23.924 36.45 46.017] [36.505 28.22 33.394]
19.630450580666768
[23.924 36.45 46.017] [38.381 26.399 36.165]
20.176455436969103
[23.924 36.45 46.017] [36.755 28.746 38.693]
16.66214731059596
[23.924 36.45 46.017] [33.38 27.283 37.714]
15.568867460416001
[23.924 36.45 46.017] [34.406 23.675 38.28]
18.246482345920818
[23.924 36.45 46.017] [34.159 22.007 41.673]
18.227062571901158
[23.924 36.45 46.017] [35.955 18.936 42.908]
21.474427536025264
[23.924 36.45 46.017] [34.706 17.233 38.93]
23.146709960596997
[23.924 36.45 46.017] [31.368 19.002 38.946]
20.244625978268903
[23.924 36.45 46.017] [30.539 21.779 36.516]
18.688645403024804
[23.924 36.45 46.017] [28.935 24.683 38.314]
14.930124547370665
[23.924 36.45 46.017] [28.107 28.322 37.665]
12.38215558778035
[23.924 36.45 46.017] [28.588 30.749 40.53]
9.184849808244012
[23.924 3

[25.261 20.813 51.393] [17.546 29.354 48.585]
11.847141849408237
[25.261 20.813 51.393] [18.866 26.664 46.239]
10.084341426191402
[25.261 20.813 51.393] [20.453 23.562 47.773]
6.616514565842049
[25.261 20.813 51.393] [23.035 21.371 46.059]
5.806719900253501
[25.261 20.813 51.393] [25.646 18.848 47.0]
4.827825493946524
[25.261 20.813 51.393] [28.718 20.133 48.765]
4.395410447273384
[25.261 20.813 51.393] [32.0 19.401 46.98]
8.178168132289777
[25.261 20.813 51.393] [36.089 23.015 46.719]
11.997527411929509
[25.261 20.813 51.393] [36.72 25.003 43.587]
14.484419801980332
[25.261 20.813 51.393] [39.048 23.407 41.025]
17.444358085065787
[25.261 20.813 51.393] [29.853 19.787 28.915]
22.96518286450165
[25.261 20.813 51.393] [25.026 20.183 28.753]
22.64998289182577
[25.261 20.813 51.393] [25.222 26.703 26.873]
25.21753399918398
[25.261 20.813 51.393] [27.356 27.5 29.894]
22.612208980990783
[25.261 20.813 51.393] [31.311 31.071 31.701]
23.01312512458923
[25.261 20.813 51.393] [33.232 27.844 31.4

[20.839 32.461 48.545] [25.222 26.703 26.873]
22.848212993580045
[20.839 32.461 48.545] [27.356 27.5 29.894]
20.370140181157325
[20.839 32.461 48.545] [31.311 31.071 31.701]
19.882535552589868
[20.839 32.461 48.545] [33.232 27.844 31.485]
21.58579945241779
[20.839 32.461 48.545] [36.505 28.22 33.394]
22.202757441363005
[20.839 32.461 48.545] [38.381 26.399 36.165]
22.309953115145717
[20.839 32.461 48.545] [36.755 28.746 38.693]
19.08355797538814
[20.839 32.461 48.545] [33.38 27.283 37.714]
17.36084462231029
[20.839 32.461 48.545] [34.406 23.675 38.28]
19.147519682716087
[20.839 32.461 48.545] [34.159 22.007 41.673]
18.273831015963783
[20.839 32.461 48.545] [35.955 18.936 42.908]
21.052193472415173
[20.839 32.461 48.545] [34.706 17.233 38.93]
22.729582002315837
[20.839 32.461 48.545] [31.368 19.002 38.946]
19.59962558315847
[20.839 32.461 48.545] [30.539 21.779 36.516]
18.785418946619213
[20.839 32.461 48.545] [28.935 24.683 38.314]
15.18933379052551
[20.839 32.461 48.545] [28.107 28.32

[18.864 28.694 37.642] [19.422 19.09 33.554]
10.452747198703316
[18.864 28.694 37.642] [18.879 16.451 36.194]
12.328340439815893
[18.864 28.694 37.642] [21.501 14.986 38.441]
13.982182733750834
[18.864 28.694 37.642] [24.7 13.704 36.885]
16.103789771355064
[18.864 28.694 37.642] [29.897 15.594 36.366]
17.174552832606732
[18.864 28.694 37.642] [27.539 18.485 37.022]
13.411327525640406
[18.864 28.694 37.642] [26.592 19.926 40.406]
12.009975187318247
[18.864 28.694 37.642] [23.561 18.022 41.764]
12.367064202954555
[18.864 28.694 37.642] [20.42 19.858 42.837]
10.367451808424285
[18.864 28.694 37.642] [19.052 18.576 46.142]
13.215871821412312
[18.864 28.694 37.642] [16.28 20.967 47.051]
12.446399720401075
[18.864 28.694 37.642] [17.546 29.354 48.585]
11.041828335923356
[18.864 28.694 37.642] [18.866 26.664 46.239]
8.833420232276957
[18.864 28.694 37.642] [20.453 23.562 47.773]
11.467323401735907
[18.864 28.694 37.642] [23.035 21.371 46.059]
11.910896649706935
[18.864 28.694 37.642] [25.646 

[19.365 22.563 37.21] [28.935 24.683 38.314]
9.863980738018501
[19.365 22.563 37.21] [28.107 28.322 37.665]
10.478342903341158
[19.365 22.563 37.21] [28.588 30.749 40.53]
12.770932816360755
[19.365 22.563 37.21] [26.416 33.292 38.708]
12.92563522616974
[19.365 22.563 37.21] [24.982 35.77 41.238]
14.90638527611574
[19.365 22.563 37.21] [27.459 34.429 43.805]
15.8053414072585
[19.365 22.563 37.21] [30.703 35.641 42.235]
18.023178215841956
[19.365 22.563 37.21] [36.278 39.771 34.52]
24.27758087207208
[16.128 20.615 37.651] [19.422 19.09 33.554]
5.4737071532920005
[16.128 20.615 37.651] [18.879 16.451 36.194]
5.1990139449707184
[16.128 20.615 37.651] [21.501 14.986 38.441]
7.821692272136509
[16.128 20.615 37.651] [24.7 13.704 36.885]
11.037565900143019
[16.128 20.615 37.651] [29.897 15.594 36.366]
14.71213876361965
[16.128 20.615 37.651] [27.539 18.485 37.022]
11.625122020864987
[16.128 20.615 37.651] [26.592 19.926 40.406]
10.842510871564757
[16.128 20.615 37.651] [23.561 18.022 41.764]
8

[29.897 15.594 36.366] [23.561 18.022 41.764]
8.670552692879504
[29.897 15.594 36.366] [20.42 19.858 42.837]
12.242102188758269
[29.897 15.594 36.366] [19.052 18.576 46.142]
14.902232215342774
[29.897 15.594 36.366] [16.28 20.967 47.051]
18.12349422710753
[29.897 15.594 36.366] [17.546 29.354 48.585]
22.16277875177208
[29.897 15.594 36.366] [18.866 26.664 46.239]
18.485237082601888
[29.897 15.594 36.366] [20.453 23.562 47.773]
16.816593263797518
[29.897 15.594 36.366] [23.035 21.371 46.059]
13.20662795720391
[29.897 15.594 36.366] [25.646 18.848 47.0]
11.905522794064945
[29.897 15.594 36.366] [28.718 20.133 48.765]
13.256234872692925
[29.897 15.594 36.366] [32.0 19.401 46.98]
11.470521086681282
[29.897 15.594 36.366] [36.089 23.015 46.719]
14.163216936840305
[29.897 15.594 36.366] [36.72 25.003 43.587]
13.683035153064544
[29.897 15.594 36.366] [39.048 23.407 41.025]
12.903102378885476
[29.897 15.594 36.366] [29.853 19.787 28.915]
8.549888069442781
[29.897 15.594 36.366] [25.026 20.183 

[19.052 18.576 46.142] [26.416 33.292 38.708]
18.056951791484636
[19.052 18.576 46.142] [24.982 35.77 41.238]
18.83740300572242
[19.052 18.576 46.142] [27.459 34.429 43.805]
18.095768206959328
[19.052 18.576 46.142] [30.703 35.641 42.235]
21.02913871274808
[19.052 18.576 46.142] [36.278 39.771 34.52]
29.68221664566176
[16.28 20.967 47.051] [17.546 29.354 48.585]
8.61961025801051
[16.28 20.967 47.051] [18.866 26.664 46.239]
6.3089261368318486
[16.28 20.967 47.051] [20.453 23.562 47.773]
4.966813666728399
[16.28 20.967 47.051] [23.035 21.371 46.059]
6.839393613471884
[16.28 20.967 47.051] [25.646 18.848 47.0]
9.602849472942914
[16.28 20.967 47.051] [28.718 20.133 48.765]
12.583210877991355
[16.28 20.967 47.051] [32.0 19.401 46.98]
15.797968128844923
[16.28 20.967 47.051] [36.089 23.015 46.719]
19.917354467900598
[16.28 20.967 47.051] [36.72 25.003 43.587]
21.120657944297093
[16.28 20.967 47.051] [39.048 23.407 41.025]
23.678008784524092
[16.28 20.967 47.051] [29.853 19.787 28.915]
22.683

19.238281160228425
[32.0 19.401 46.98] [33.232 27.844 31.485]
17.688897591427224
[32.0 19.401 46.98] [36.505 28.22 33.394]
16.81217362508489
[32.0 19.401 46.98] [38.381 26.399 36.165]
14.375443993143307
[32.0 19.401 46.98] [36.755 28.746 38.693]
13.364633141242598
[32.0 19.401 46.98] [33.38 27.283 37.714]
12.242919586438523
[32.0 19.401 46.98] [34.406 23.675 38.28]
9.987287519642154
[32.0 19.401 46.98] [34.159 22.007 41.673]
6.2941850941960675
[32.0 19.401 46.98] [35.955 18.936 42.908]
5.6955626587721735
[32.0 19.401 46.98] [34.706 17.233 38.93]
8.76499629206995
[32.0 19.401 46.98] [31.368 19.002 38.946]
8.068691405674155
[32.0 19.401 46.98] [30.539 21.779 36.516]
10.829806138615778
[32.0 19.401 46.98] [28.935 24.683 38.314]
10.601570874167656
[32.0 19.401 46.98] [28.107 28.322 37.665]
13.472524447927343
[32.0 19.401 46.98] [28.588 30.749 40.53]
13.491528749552435
[32.0 19.401 46.98] [26.416 33.292 38.708]
17.104587717919422
[32.0 19.401 46.98] [24.982 35.77 41.238]
18.712750973600865


[38.381 26.399 36.165] [36.755 28.746 38.693]
3.813537596510617
[38.381 26.399 36.165] [33.38 27.283 37.714]
5.309506380069618
[38.381 26.399 36.165] [34.406 23.675 38.28]
5.262511377659912
[38.381 26.399 36.165] [34.159 22.007 41.673]
8.212978266134645
[38.381 26.399 36.165] [35.955 18.936 42.908]
10.346491869227949
[38.381 26.399 36.165] [34.706 17.233 38.93]
10.25506733278724
[38.381 26.399 36.165] [31.368 19.002 38.946]
10.565592221924904
[38.381 26.399 36.165] [30.539 21.779 36.516]
9.108488623256878
[38.381 26.399 36.165] [28.935 24.683 38.314]
9.838179353925199
[38.381 26.399 36.165] [28.107 28.322 37.665]
10.559498330886747
[38.381 26.399 36.165] [28.588 30.749 40.53]
11.57059090971589
[38.381 26.399 36.165] [26.416 33.292 38.708]
14.040709490620479
[38.381 26.399 36.165] [24.982 35.77 41.238]
17.11970125323453
[38.381 26.399 36.165] [27.459 34.429 43.805]
15.560867070957197
[38.381 26.399 36.165] [30.703 35.641 42.235]
13.461469013447232
[38.381 26.399 36.165] [36.278 39.771 3

In [17]:
#print(type(residue_pair1))
#residue_pair1,2의 type은 numpy.float64이고 euclidean distance에 테스트했던 자료는 상수로 
#이 차이 때문에 math모듈의 함수 적용이 어려운 것으로 추측된다. 데이터 타입 변환을 고려해볼 수 있다.

<class 'numpy.float64'>


In [46]:
for i in range(len(pdb4)):
    for j in range(i+1,len(pdb4)):
        residue_pair1_1=pdb4.iloc[i][['residue_name','residue_number','chain_id']].values
        residue_pair2_1=pdb4.iloc[j][['residue_name','residue_number','chain_id']].values
        residue_pair1_2=pdb4.iloc[i][['x_coord','y_coord','z_coord']].values
        residue_pair2_2=pdb4.iloc[j][['x_coord','y_coord','z_coord']].values
        print(residue_pair1_1,residue_pair2_1,euclidean_distance(residue_pair1_2,residue_pair2_2),i,j)

['LEU' 595 'A'] ['GLY' 596 'A'] 3.8009352796384195 0 1
['LEU' 595 'A'] ['ALA' 597 'A'] 7.139153241106401 0 2
['LEU' 595 'A'] ['GLY' 601 'A'] 11.17781843652866 0 3
['LEU' 595 'A'] ['LYS' 602 'A'] 7.541626217202762 0 4
['LEU' 595 'A'] ['VAL' 603 'A'] 5.317814400672518 0 5
['LEU' 595 'A'] ['VAL' 604 'A'] 5.102479691287362 0 6
['LEU' 595 'A'] ['VAL' 620 'A'] 11.192119861759881 0 7
['LEU' 595 'A'] ['ALA' 621 'A'] 8.23504426217613 0 8
['LEU' 595 'A'] ['VAL' 622 'A'] 9.190084656846205 0 9
['LEU' 595 'A'] ['LYS' 623 'A'] 9.439753651446631 0 10
['LEU' 595 'A'] ['MET' 624 'A'] 11.520001171874942 0 11
['LEU' 595 'A'] ['ALA' 636 'A'] 19.450930080589977 0 12
['LEU' 595 'A'] ['LEU' 637 'A'] 16.85429657387101 0 13
['LEU' 595 'A'] ['MET' 638 'A'] 19.873861476824278 0 14
['LEU' 595 'A'] ['SER' 639 'A'] 21.07234047276192 0 15
['LEU' 595 'A'] ['GLU' 640 'A'] 17.906809766119704 0 16
['LEU' 595 'A'] ['LEU' 641 'A'] 18.260040032814825 0 17
['LEU' 595 'A'] ['LYS' 642 'A'] 21.930720849985757 0 18
['LEU' 595 '

['LYS' 602 'A'] ['LEU' 637 'A'] 11.043686567446581 4 13
['LYS' 602 'A'] ['MET' 638 'A'] 14.402867075690175 4 14
['LYS' 602 'A'] ['SER' 639 'A'] 16.048880739789922 4 15
['LYS' 602 'A'] ['GLU' 640 'A'] 13.805465946501043 4 16
['LYS' 602 'A'] ['LEU' 641 'A'] 14.52662032270411 4 17
['LYS' 602 'A'] ['LYS' 642 'A'] 18.183387500683146 4 18
['LYS' 602 'A'] ['VAL' 643 'A'] 18.35495197487588 4 19
['LYS' 602 'A'] ['LEU' 644 'A'] 17.239770358099324 4 20
['LYS' 602 'A'] ['SER' 645 'A'] 19.78216504834595 4 21
['LYS' 602 'A'] ['LEU' 647 'A'] 21.93944324726587 4 22
['LYS' 602 'A'] ['GLY' 648 'A'] 22.49613811301842 4 23
['LYS' 602 'A'] ['ASN' 649 'A'] 21.92513954345559 4 24
['LYS' 602 'A'] ['HIS' 650 'A'] 23.32578189471899 4 25
['LYS' 602 'A'] ['ASN' 652 'A'] 22.225230549985305 4 26
['LYS' 602 'A'] ['ILE' 653 'A'] 19.186443286862737 4 27
['LYS' 602 'A'] ['VAL' 654 'A'] 16.137655405913222 4 28
['LYS' 602 'A'] ['ASN' 655 'A'] 17.4934920756263 4 29
['LYS' 602 'A'] ['LEU' 656 'A'] 16.252083712558214 4 30
[

['ALA' 621 'A'] ['ALA' 794 'A'] 19.733429580283303 8 49
['ALA' 621 'A'] ['ALA' 795 'A'] 18.411658833467452 8 50
['ALA' 621 'A'] ['ARG' 796 'A'] 16.018766806467973 8 51
['ALA' 621 'A'] ['ASN' 797 'A'] 14.333327073642048 8 52
['ALA' 621 'A'] ['ILE' 798 'A'] 14.083099836328646 8 53
['ALA' 621 'A'] ['LEU' 799 'A'] 11.551123105568564 8 54
['ALA' 621 'A'] ['LEU' 800 'A'] 13.048087790937029 8 55
['ALA' 621 'A'] ['THR' 806 'A'] 15.345418632282406 8 56
['ALA' 621 'A'] ['LYS' 807 'A'] 12.913314601604037 8 57
['ALA' 621 'A'] ['ILE' 808 'A'] 13.98111118616829 8 58
['ALA' 621 'A'] ['CYS' 809 'A'] 11.620851517853588 8 59
['ALA' 621 'A'] ['ASP' 810 'A'] 12.79317357030694 8 60
['ALA' 621 'A'] ['PHE' 811 'A'] 11.530567592274023 8 61
['ALA' 621 'A'] ['GLY' 812 'A'] 14.24121448472707 8 62
['ALA' 621 'A'] ['LEU' 813 'A'] 14.393404114385177 8 63
['ALA' 621 'A'] ['ALA' 814 'A'] 11.958434721985986 8 64
['ALA' 621 'A'] ['ARG' 815 'A'] 14.50931221664211 8 65
['ALA' 621 'A'] ['TYR' 823 'A'] 24.076334044035857 8

['LEU' 637 'A'] ['LEU' 783 'A'] 18.64837904483926 13 44
['LEU' 637 'A'] ['ILE' 789 'A'] 16.85932931643486 13 45
['LEU' 637 'A'] ['HIS' 790 'A'] 15.358564418590692 13 46
['LEU' 637 'A'] ['ASP' 792 'A'] 16.37660557014182 13 47
['LEU' 637 'A'] ['LEU' 793 'A'] 18.603813480036827 13 48
['LEU' 637 'A'] ['ALA' 794 'A'] 20.53445285367984 13 49
['LEU' 637 'A'] ['ALA' 795 'A'] 21.889189158120956 13 50
['LEU' 637 'A'] ['ARG' 796 'A'] 19.362111377636484 13 51
['LEU' 637 'A'] ['ASN' 797 'A'] 16.636195899303427 13 52
['LEU' 637 'A'] ['ILE' 798 'A'] 18.859928366778064 13 53
['LEU' 637 'A'] ['LEU' 799 'A'] 19.301286019330423 13 54
['LEU' 637 'A'] ['LEU' 800 'A'] 22.591724192721546 13 55
['LEU' 637 'A'] ['THR' 806 'A'] 22.706465554991162 13 56
['LEU' 637 'A'] ['LYS' 807 'A'] 19.077419767882656 13 57
['LEU' 637 'A'] ['ILE' 808 'A'] 17.078096468869123 13 58
['LEU' 637 'A'] ['CYS' 809 'A'] 13.711411998769492 13 59
['LEU' 637 'A'] ['ASP' 810 'A'] 11.482144616751699 13 60
['LEU' 637 'A'] ['PHE' 811 'A'] 10.

['LYS' 642 'A'] ['ASN' 797 'A'] 18.844551414135605 18 52
['LYS' 642 'A'] ['ILE' 798 'A'] 19.858904753283852 18 53
['LYS' 642 'A'] ['LEU' 799 'A'] 20.313175871832545 18 54
['LYS' 642 'A'] ['LEU' 800 'A'] 22.988953260207392 18 55
['LYS' 642 'A'] ['THR' 806 'A'] 21.69743832806076 18 56
['LYS' 642 'A'] ['LYS' 807 'A'] 17.963155986629964 18 57
['LYS' 642 'A'] ['ILE' 808 'A'] 16.283266779120215 18 58
['LYS' 642 'A'] ['CYS' 809 'A'] 14.351596879790067 18 59
['LYS' 642 'A'] ['ASP' 810 'A'] 13.803649698539875 18 60
['LYS' 642 'A'] ['PHE' 811 'A'] 15.358880883710247 18 61
['LYS' 642 'A'] ['GLY' 812 'A'] 14.31589763165412 18 62
['LYS' 642 'A'] ['LEU' 813 'A'] 15.287167330803966 18 63
['LYS' 642 'A'] ['ALA' 814 'A'] 17.109475795593507 18 64
['LYS' 642 'A'] ['ARG' 815 'A'] 19.780280938348675 18 65
['LYS' 642 'A'] ['TYR' 823 'A'] 26.145198297201723 18 66
['VAL' 643 'A'] ['LEU' 644 'A'] 3.8110662550000343 19 20
['VAL' 643 'A'] ['SER' 645 'A'] 5.361625126768936 19 21
['VAL' 643 'A'] ['LEU' 647 'A'] 6.

['ASN' 649 'A'] ['MET' 780 'A'] 13.548069272040207 24 43
['ASN' 649 'A'] ['LEU' 783 'A'] 11.545205844851793 24 44
['ASN' 649 'A'] ['ILE' 789 'A'] 16.8805377284019 24 45
['ASN' 649 'A'] ['HIS' 790 'A'] 16.24599735319442 24 46
['ASN' 649 'A'] ['ASP' 792 'A'] 20.00977073831682 24 47
['ASN' 649 'A'] ['LEU' 793 'A'] 18.743811271990552 24 48
['ASN' 649 'A'] ['ALA' 794 'A'] 20.633249404783534 24 49
['ASN' 649 'A'] ['ALA' 795 'A'] 20.502954543187183 24 50
['ASN' 649 'A'] ['ARG' 796 'A'] 20.544722436674583 24 51
['ASN' 649 'A'] ['ASN' 797 'A'] 17.113017822698602 24 52
['ASN' 649 'A'] ['ILE' 798 'A'] 15.55839538641437 24 53
['ASN' 649 'A'] ['LEU' 799 'A'] 14.831224797702985 24 54
['ASN' 649 'A'] ['LEU' 800 'A'] 15.635686905281773 24 55
['ASN' 649 'A'] ['THR' 806 'A'] 13.403736605887183 24 56
['ASN' 649 'A'] ['LYS' 807 'A'] 10.664941162519366 24 57
['ASN' 649 'A'] ['ILE' 808 'A'] 11.468910933475767 24 58
['ASN' 649 'A'] ['CYS' 809 'A'] 12.219340980593019 24 59
['ASN' 649 'A'] ['ASP' 810 'A'] 14.9

['LEU' 657 'A'] ['ASP' 677 'A'] 18.973470373128897 31 41
['LEU' 657 'A'] ['LEU' 678 'A'] 21.198166571663695 31 42
['LEU' 657 'A'] ['MET' 780 'A'] 20.369036575154954 31 43
['LEU' 657 'A'] ['LEU' 783 'A'] 18.456663999759005 31 44
['LEU' 657 'A'] ['ILE' 789 'A'] 21.80393060895214 31 45
['LEU' 657 'A'] ['HIS' 790 'A'] 20.312353285624003 31 46
['LEU' 657 'A'] ['ASP' 792 'A'] 22.692522711236844 31 47
['LEU' 657 'A'] ['LEU' 793 'A'] 22.400800722295624 31 48
['LEU' 657 'A'] ['ALA' 794 'A'] 23.666969577873722 31 49
['LEU' 657 'A'] ['ALA' 795 'A'] 23.11601390811141 31 50
['LEU' 657 'A'] ['ARG' 796 'A'] 21.732756613002415 31 51
['LEU' 657 'A'] ['ASN' 797 'A'] 18.765250251462145 31 52
['LEU' 657 'A'] ['ILE' 798 'A'] 17.987666913749543 31 53
['LEU' 657 'A'] ['LEU' 799 'A'] 16.123435458983298 31 54
['LEU' 657 'A'] ['LEU' 800 'A'] 17.2133600729201 31 55
['LEU' 657 'A'] ['THR' 806 'A'] 17.287692413968966 31 56
['LEU' 657 'A'] ['LYS' 807 'A'] 14.270520242794236 31 57
['LEU' 657 'A'] ['ILE' 808 'A'] 15.

['ILE' 669 'A'] ['CYS' 809 'A'] 12.754357921902619 35 59
['ILE' 669 'A'] ['ASP' 810 'A'] 13.543004836446011 35 60
['ILE' 669 'A'] ['PHE' 811 'A'] 13.049607005576835 35 61
['ILE' 669 'A'] ['GLY' 812 'A'] 14.574103540183874 35 62
['ILE' 669 'A'] ['LEU' 813 'A'] 14.568916569189353 35 63
['ILE' 669 'A'] ['ALA' 814 'A'] 13.524819740018721 35 64
['ILE' 669 'A'] ['ARG' 815 'A'] 16.781960106018605 35 65
['ILE' 669 'A'] ['TYR' 823 'A'] 26.245081729726046 35 66
['THR' 670 'A'] ['GLU' 671 'A'] 3.75077738608945 36 37
['THR' 670 'A'] ['TYR' 672 'A'] 6.414948869632557 36 38
['THR' 670 'A'] ['CYS' 673 'A'] 9.224985962048939 36 39
['THR' 670 'A'] ['GLY' 676 'A'] 13.173657502759056 36 40
['THR' 670 'A'] ['ASP' 677 'A'] 14.372941000365929 36 41
['THR' 670 'A'] ['LEU' 678 'A'] 16.908655209684778 36 42
['THR' 670 'A'] ['MET' 780 'A'] 18.517853979335726 36 43
['THR' 670 'A'] ['LEU' 783 'A'] 17.460614565358227 36 44
['THR' 670 'A'] ['ILE' 789 'A'] 20.032867717828115 36 45
['THR' 670 'A'] ['HIS' 790 'A'] 17.

['ILE' 789 'A'] ['ILE' 808 'A'] 12.062492031085448 45 58
['ILE' 789 'A'] ['CYS' 809 'A'] 12.19685410259547 45 59
['ILE' 789 'A'] ['ASP' 810 'A'] 11.287676908912655 45 60
['ILE' 789 'A'] ['PHE' 811 'A'] 14.63604184880598 45 61
['ILE' 789 'A'] ['GLY' 812 'A'] 13.598080085070832 45 62
['ILE' 789 'A'] ['LEU' 813 'A'] 16.98885852551607 45 63
['ILE' 789 'A'] ['ALA' 814 'A'] 18.745342594895405 45 64
['ILE' 789 'A'] ['ARG' 815 'A'] 18.59893139403444 45 65
['ILE' 789 'A'] ['TYR' 823 'A'] 18.747916390895284 45 66
['HIS' 790 'A'] ['ASP' 792 'A'] 5.626661088069905 46 47
['HIS' 790 'A'] ['LEU' 793 'A'] 6.097293907956216 46 48
['HIS' 790 'A'] ['ALA' 794 'A'] 9.822046680809454 46 49
['HIS' 790 'A'] ['ALA' 795 'A'] 12.73138904440517 46 50
['HIS' 790 'A'] ['ARG' 796 'A'] 12.935073173353137 46 51
['HIS' 790 'A'] ['ASN' 797 'A'] 9.873604458352585 46 52
['HIS' 790 'A'] ['ILE' 798 'A'] 11.604228582719317 46 53
['HIS' 790 'A'] ['LEU' 799 'A'] 14.669652313534906 46 54
['HIS' 790 'A'] ['LEU' 800 'A'] 17.79463